### ISSUE TITLE
Textlint Github Action

### ISSUE THREAD

**Issue by dannytce** [strvcom/code-quality-tools#104]
Let's create an action that could be used on our repositories regardless if it's a frontend, backend, or any other (non-javascript) platform! 

The idea is simple - to minify typos and silly grammar mistakes from our readmes, ADRs and any other markdown related content :) 

---

@robertrossmann a quick question for you - do you think that this monorepo is a good place where to add our own github actions? Or shall we create them in a separate repository? 

Standalone repository make sense in terms of easier usage.
This monorepo make sense to have everything together under one roof.

**Comment by robertrossmann** [comment]
@dannytce I think Actions should reside in their own repository to be functional, otherwise you'd have to build and publish a Docker image of them. The repository must be a fully functional representation of the code the Action will run. There is no "compile" or "npm install" step available before the Action is used in a project - Github just downloads the repo and runs it as-is.

Personally I'd probably go the standalone repo route... 🤔
