### ISSUE TITLE
Add Dependabot

### ISSUE THREAD

**Issue by dannytce** [strvcom/code-quality-tools#23]
Let's install Greenkeeper or a similar service to get an automatical update of dependencies.

For example, eslint-plugin-import is out of date. And it doesn't work well with `@typescript-eslint/parser`, which throws errors on types and interfaces for `import/named` rule

**Comment by robertrossmann** [comment]
Client-side, _package-lock.json_ files are not used during `npm install` and we use `compatible-with` (`^`) semver ranges for all deps, so if there is an update for a plugin you just upgrade it in your project and you are all set.

Greenkeeper notifications would be great, though, because when a new release is made we can evaluate all the new rules and rule changes available and update our rulesets to make use of them. 👍

**Comment by dannytce** [comment]
*Update*: let's go with Dependatbot instead! :)

**Comment by dannytce** [comment]
@robertrossmann looks like Dependabot supports monorepos managed by lerna :) But there is a note:

> Note: Dependabot doesn't support linking local/unpublished dependencies that require lerna bootstrap. You can convert local dependencies to use file: imports instead which are supported by Depenedabot with lerna link convert.
https://dependabot.com/blog/lerna-support/

Afaik, it's not related to our case, right?

**Comment by robertrossmann** [comment]
Brace yourselves, it's coming! ❄️ 🤖
