### ISSUE TITLE
@typescript-eslint/explicit-function-return-type vs inference

### ISSUE THREAD

**Issue by lucasconstantino** [strvcom/code-quality-tools#24]
`@typescript-eslint/explicit-function-return-type` enforces every function defines a returning type. Most of the time, though, TypeScript can infer the returning type from the return value. This rules causes many redundant and unnecessary code.  

https://github.com/strvcom/code-quality-tools/blob/6f7d241c7be727ec5aa1e048b193cce655b3cef5/packages/eslint-config-typescript/index.js#L72-L74

Ref.: https://github.com/typescript-eslint/typescript-eslint/issues/434

**Comment by robertrossmann** [comment]
@lucasconstantino for inline function expressions (like callbacks etc.) the return types should be optional already, I hope. 😇

As for function declarations, I think the original idea for requiring explicit return types was twofold:

- it kinda somewhat forces you to think in advance about what your function will return
- it kinda somewhat makes changing a function's return type more explicit rather than "accidental"/implicit, ie. by a seemingly innocent bug fix in the function's body you accidentally return a different type... Sometimes changing a return type means something somewhere will break. 😄

However, I do not have hands-on experience with TypeScript so it is possible that these arguments are not really valid because TS can cover the dangerous aspects of changing a function's return type by accident.

**Comment by bsunderhus** [comment]
For my experience, enforcing a return type declaration can be verbose in scenarios involving multiple [generics](https://www.typescriptlang.org/docs/handbook/generics.html), and more complex types (`Pick`, `Exclude`, `ReturnType`, `Parameters`, etc).

It is definitely a good idea to help the developer create a mindset on knowing exactly what he is doing, but sometimes what the developer is trying to achieve can become extremely verbose when mixing more complex types and generic. That would make it quite annoying to keep the redundancy of redeclaring the return type.

I feel like this is a good rule for beginners but a pain for someone who has more experience with the language.

**Comment by lucasconstantino** [comment]
I agree with both of you. I think the issue here is there are two conflicting goals.

Maybe we could move this rule to `@strv/eslint-config-typescript/style`? Also, I think we should keep in mind people can always override their config... in that case, ESLint opt-outs are generally easier than opt-ins.

**Comment by robertrossmann** [comment]
After thorough consideration I think it's best to not modify the rule:

- it's easier to turn it off than it is to turn it on on a per-project basis
- since this ruleset is public we have to assume that it may be used not only for applications but also for libraries. While TS should, in theory, catch all the breakages caused by implicitly changing a return value (either intentionally or by accident), it will never catch breakages caused in other projects using your library. Therefore, changing a return value should really trigger a big, red flag in the developer's head so that they fully consider the implications. This rule definitely helps in situations where a return value is changed accidentally rather than intentionally, therefore reducing the chance of introducing a breaking change in a library by accident.

I understand that this rule may cause unnecessary churn for you while working on an end product and I believe it is safe to turn this rule off, as long as you are the final consumer of the code you are working on.

Thanks for the feedback and for the discussion! 🍻 ❤️
