### ISSUE TITLE
Possible improvements [config-react]

### ISSUE THREAD

**Issue by developer239** [strvcom/code-quality-tools#96]
Hello 👋 
this is the second batch of possible improvements.

**Missing rules:**

- [react/button-has-type](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/button-has-type.md) error
- [react/no-children-prop](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-children-prop.md) error
- [react/prefer-es6-class](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prefer-es6-class.md) error (although probably not necessary anymore)
- [react/prefer-read-only-props](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prefer-read-only-props.md) error (not sure how this works with typescript)
- [react/prefer-stateless-function](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prefer-stateless-function.md) error
- [react/sort-prop-types](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-prop-types.md) ? (I turned this off in my projects but if it works with typescript and is auto-fixable then it could be useful but I think we can ignore this rule)
- [react/jsx-boolean-value](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-boolean-value.md) error
- [react/jsx-child-element-spacing](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-child-element-spacing.md) error
- [react/jsx-closing-tag-location](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-closing-tag-location.md) error
- [https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-wrap-multilines.md](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-wrap-multilines.md) error

**Rules that I would change:**
Mostly config code style improvement so feel free to ignore.

- [react/boolean-prop-naming](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/boolean-prop-naming.md) error
- [react/no-danger](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-danger.md) error
- [react/no-deprecated](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-deprecated.md) error
- [react/jsx-handler-names](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-handler-names.md) error
- [react/jsx-key](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-key.md) error
- [react/jsx-no-target-blank](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-target-blank.md) error
- [react/jsx-curly-brace-presence](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-curly-brace-presence.md) error
- [react/jsx-fragments](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-fragments.md) error
- [react/jsx-no-useless-fragment](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-useless-fragment.md) error
- [react/jsx-pascal-case](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-pascal-case.md) error
- [react/destructuring-assignment](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/destructuring-assignment.md) error
- [react/jsx-closing-bracket-location](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-closing-bracket-location.md) error
- [react/jsx-first-prop-new-line](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-first-prop-new-line.md) error
- [react/jsx-indent](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-indent.md) error
- [react/jsx-tag-spacing](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-tag-spacing.md) error
- [react/self-closing-comp](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/self-closing-comp.md) error

**Comment by xhudec** [comment]
Again, great suggestions @developer239 

## Missing rules

- [react/button-has-type](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/button-has-type.md)
    - agree
    - `warn` at least within `base` ruleset
- [react/no-children-prop](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-children-prop.md)
    - agree
    - `warn` at least within `base` ruleset
- [react/prefer-es6-class](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prefer-es6-class.md)
    - 🤷‍♂️I would it is not needed, but might be usable on some older projects where want to bring some nice refactoring
- [react/prefer-read-only-props](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prefer-read-only-props.md)
    - TS has [prefer-readonly-parameter-types](https://github.com/typescript-eslint/typescript-eslint/blob/v2.27.0/packages/eslint-plugin/docs/rules/prefer-readonly-parameter-types.md) which is already included in our [TS base config](https://github.com/strvcom/code-quality-tools/blob/master/packages/eslint-config-typescript/index.js#L300)
        - but I have it turned off on my personal projects that use STRV ESLint configs because it is not working properly when I destructure function parameters or I am missing something 🤷‍♂️

![PixelSnap 2020-05-04 at 14 09 37@2x](https://user-images.githubusercontent.com/8865760/80967715-18d18e00-8e17-11ea-9aa2-ef25788a2bc6.png)

![PixelSnap 2020-05-04 at 14 10 44@2x](https://user-images.githubusercontent.com/8865760/80967727-1bcc7e80-8e17-11ea-8303-730d83f4f3ac.png)
Note: no error about read-only from TS 😅because destructure creates new *variables* so... this is correct but confusing
- [react/prefer-stateless-function](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prefer-stateless-function.md)
    - agree
- [react/sort-prop-types](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-prop-types.md)
    - agree
    - `optional`/`style` rulesets with `warn`
- [react/jsx-boolean-value](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-boolean-value.md)
    - Generally, I would say `style` ruleset with `warn` at least
    - Personal opinion: It triggers me when I see `<MyComp isOpen={true} />` so I would even push it in `base` ruleset with error as Michal proposed
- [react/jsx-child-element-spacing](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-child-element-spacing.md)
    - agree
    - `warn` at least
    - possible conflict with `prettier`?
- [react/jsx-closing-tag-location](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-closing-tag-location.md)
    - agree
    - Formatting stuff → `style` ruleset & should be handled by `prettier`
- [react/jsx-wrap-multilines](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-wrap-multilines.md)
    - agree
    - Formatting stuff → `style` ruleset & should be handled by `prettier`

## Change to `error`

- [react/boolean-prop-naming](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/boolean-prop-naming.md)
    - Personally I would agree, but still, it feels like that it should be just a warning
- [react/no-danger](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-danger.md)
    - agree
- [react/no-deprecated](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-deprecated.md)
    - 🤔warning seems alright, but tough one
- [react/jsx-handler-names](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-handler-names.md)
    - warning seems just fine
- [react/jsx-key](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-key.md)
    - agree
- [react/jsx-no-target-blank](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-target-blank.md)
    - agree
- [react/jsx-curly-brace-presence](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-curly-brace-presence.md)
    - warning seems fine
- [react/jsx-fragments](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-fragments.md)
    - warning seems fine
- [react/jsx-no-useless-fragment](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-useless-fragment.md)
    - 🤔agree
- [react/jsx-pascal-case](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-pascal-case.md)
    - agree
- [react/destructuring-assignment](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/destructuring-assignment.md)
    - personally, I incline towards `error` as well on this one
- [react/jsx-closing-bracket-location](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-closing-bracket-location.md)
    - warning seems fine
    - handled by `prettier`
- [react/jsx-first-prop-new-line](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-first-prop-new-line.md)
    - 🤷‍♂️
    - warning seems good enough
    - handled by `prettier`
- [react/jsx-indent](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-indent.md)
    - I let `prettier` to handle this one so I have this turned off
    - the warning seems good enough
- [react/jsx-tag-spacing](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-tag-spacing.md)
    - handled by `prettier`
    - warning seems good enough
- [react/self-closing-comp](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/self-closing-comp.md)
    - handled by `prettier`
    - the warning seems good enough

cc @dannytce @robertrossmann

**Comment by developer239** [comment]
@xhudec Thank you for the review. 🙌 

- `react/prefer-read-only-prop` was really useful 👌 
- I moved most of the rules that you consider style rules to `styles`.
- I pretty much ignored (left all rules as they are) everything that is auto fixed by prettier. It is OK to commit it if the prettier fixes it. 🤷‍♂️ 

We can move the conversation and invite other people here: #107
